services:
  - type: web
    name: elda
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: |
      python create_superuser.py && gunicorn elda.wsgi:application -c gunicorn_config.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: elda-db
          property: connectionString

databases:
  - name: elda-db
    type: postgresql
    plan: free
