# Generated by Django 5.2.1 on 2025-06-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_elda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFile',
            new_name='SearchModel',
        ),
    ]
