# Generated by Django 5.2.1 on 2025-06-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_elda', '0002_rename_uploadedfile_searchmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchmodel',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='file_type',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='original_filename',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='preview_content',
            field=models.TextField(blank=True),
        ),
    ]
