# Generated by Django 5.2.3 on 2025-07-22 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NarrationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.TextField(db_index=True)),
                ('has_Credit', models.BooleanField(db_index=True, default=False)),
                ('financial_date', models.DateField(blank=True, max_length=255)),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xel.excelfile')),
            ],
            options={
                'indexes': [models.Index(fields=['narration', 'has_Credit'], name='xel_narrati_narrati_eaca86_idx')],
            },
        ),
    ]
