# Generated by Django 5.2.3 on 2025-06-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarrationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.TextField()),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xel.excelfile')),
            ],
        ),
    ]
