# Generated by Django 5.2.3 on 2025-07-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrationentry',
            name='account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='narrationentry',
            name='branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='narrationentry',
            name='client_ip_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='narrationentry',
            name='debit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='narrationentry',
            name='entry_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='narrationentry',
            name='instrument_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='narrationentry',
            name='nuban',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='narrationentry',
            name='teller',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='narrationentry',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='narrationentry',
            name='financial_date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
